module.exports = {
  apiPrefix: 'https://www.qaformath.com/zbuniserver-api/',
  noDataGood:{
    goods_name: "",
    goods_image: "",
    goods_type_id: 0,
    goods_collect: 0,
    category_id: 0,
    goods_jingle: "",
    goods_price: 0,
    goods_marketprice: 0,
    goods_serial: "",
    goods_click: 0,
    goods_salenum: 0,
    goods_spec: [],
    goods_storage: 0,
    goods_state: 0,
    goods_verify: 0,
    create_time: "",
    update_time: "",
    goods_freight: 0,
    evaluation_good_star: 0,
    evaluation_count: 0,
  }
};